name: Build & Deploy Ping

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Ping image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.ping
          push: true
          tags: madhavanar/ping-app:latest

      - name: Deploy to Civo server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 212.2.254.40
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ping
            docker compose pull
            docker compose up -d
